name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |

        # docker pull rupali1520/cockpit-frontend:prod
        # docker tag rupali1520/cockpit-frontend:prod rupali1520/cockpit-frontend-archived:latest

        docker build . -t cockpitpro.azurecr.io/cockpit_fe:latest

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: 'cockpitpro.azurecr.io'
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Image to ACR
      run: |
        docker push cockpitpro.azurecr.io/cockpit_fe:latest

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build


  #   steps:
  #   - name: Install SSH
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.VM_HOST }}
  #       username: ${{ secrets.VM_USERNAME }}
  #       password: ${{ secrets.VM_PASSWORD }}
  #       script: |
  #         sudo docker pull rupali1520/cockpit-backend:prod
  #         sudo docker stop cockpit-frontend
  #         sudo docker rm -f cockpit-frontend
  #         sudo docker run -dp 4200:4200 --name cockpit-frontend rupali1520/cockpit-frontend:prod
